// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.BUS.Context;

namespace _1.BUS.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1.BUS.DomainClass.Ban", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.CaLV", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("Ma");

                    b.ToTable("CaLV");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.ChucVu", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ma");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.HoaDon", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaVC")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayTao")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("Ma");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaVC");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.HoaDonCT", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaHD")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("DonGia")
                        .IsRequired()
                        .HasColumnType("money");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaSP", "MaHD");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaHD");

                    b.ToTable("HoaDonCT");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.KhachHang", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("DiemTL")
                        .HasColumnType("int");

                    b.Property<string>("MaLKH")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ma");

                    b.HasIndex("MaLKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.LoaiKhachHang", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ma");

                    b.ToTable("LoaiKhachHang");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.LoaiSanPham", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ma");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.NhanVien", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaCLV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaCV")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.HasIndex("MaCLV");

                    b.HasIndex("MaCV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.SanPham", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Gia")
                        .IsRequired()
                        .HasColumnType("money");

                    b.Property<string>("MaLsp")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.HasIndex("MaLsp");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.Voucher", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("GiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayBatDau")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.HoaDon", b =>
                {
                    b.HasOne("_1.BUS.DomainClass.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.BUS.DomainClass.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.BUS.DomainClass.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("MaVC");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.HoaDonCT", b =>
                {
                    b.HasOne("_1.BUS.DomainClass.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.BUS.DomainClass.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.BUS.DomainClass.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.KhachHang", b =>
                {
                    b.HasOne("_1.BUS.DomainClass.LoaiKhachHang", "LoaiKhachHang")
                        .WithMany()
                        .HasForeignKey("MaLKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiKhachHang");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.NhanVien", b =>
                {
                    b.HasOne("_1.BUS.DomainClass.CaLV", "CaLv")
                        .WithMany()
                        .HasForeignKey("MaCLV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.BUS.DomainClass.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLv");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("_1.BUS.DomainClass.SanPham", b =>
                {
                    b.HasOne("_1.BUS.DomainClass.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("MaLsp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
